### ISSUE TITLE
IntGen's training and test

### ISSUE THREAD

**Issue by wuxiaofei01** [oakink/OakInk-Grasp-Generation#2]
Hello author, when I read your paper, I found that IntGen is divided into 4 columns. Do you train on 4 objects separately and then test on 4 objects?
So is it divided into 4 independent experiments?
```
DATASET:
  TRAIN:
    TYPE: OIShape
    DATA_SPLIT: train
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: ["use", "hold"]
    
  VAL:
    TYPE: OIShape
    DATA_SPLIT: val
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: ["use", "hold"]

  TEST:
    TYPE: OIShape
    DATA_SPLIT: test
    DATA_ROOT: ./data
    DATA_MODE: intent
    OBJ_CATES: ["trigger_sprayer"]
    INTENT_MODE: "all"

```
